create extension if not exists pgcrypto;
create table if not exists public.goals(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,description text default '',category text default 'Personal',deadline date,created_at timestamptz default now());
create table if not exists public.tasks(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,goal_id uuid not null references public.goals(id) on delete cascade,title text not null,due_date date,duration text default '30 min',done boolean default false,adjusted boolean default false,created_at timestamptz default now());
create table if not exists public.memories(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,category text default 'context',label text not null,value text not null,source text default 'LifePilot',created_at timestamptz default now());
create table if not exists public.agent_messages(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,role text not null check(role in('user','assistant')),content text not null,created_at timestamptz default now());
create table if not exists public.activity(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,kind text not null,title text not null,detail text default '',created_at timestamptz default now());
alter table public.goals add column if not exists outcomes text[] default '{}';alter table public.goals add column if not exists milestones text[] default '{}';alter table public.tasks add column if not exists purpose text default '';alter table public.tasks add column if not exists steps text[] default '{}';alter table public.tasks add column if not exists result text default '';
alter table public.goals enable row level security;alter table public.tasks enable row level security;alter table public.memories enable row level security;alter table public.agent_messages enable row level security;alter table public.activity enable row level security;
drop policy if exists "Users can manage their goals" on public.goals;create policy "Users can manage their goals" on public.goals for all using(auth.uid()=user_id) with check(auth.uid()=user_id);drop policy if exists "Users can manage their tasks" on public.tasks;create policy "Users can manage their tasks" on public.tasks for all using(auth.uid()=user_id) with check(auth.uid()=user_id);drop policy if exists "Users can manage their memories" on public.memories;create policy "Users can manage their memories" on public.memories for all using(auth.uid()=user_id) with check(auth.uid()=user_id);drop policy if exists "Users can manage their agent messages" on public.agent_messages;create policy "Users can manage their agent messages" on public.agent_messages for all using(auth.uid()=user_id) with check(auth.uid()=user_id);drop policy if exists "Users can manage their activity" on public.activity;create policy "Users can manage their activity" on public.activity for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
