'use client'
import {createContext,useCallback,useContext,useEffect,useMemo,useState} from 'react'
import {createClient} from './supabase/client';import {addDays,TODAY} from './dates';import type {Activity,ChatMessage,Goal,MemoryItem} from './types'
type Ctx={goals:Goal[];memories:MemoryItem[];messages:ChatMessage[];activity:Activity[];isThinking:boolean;createGoal:(t:string,d:string)=>Promise<string>;toggleTask:(g:string,t:string)=>Promise<void>;replanGoal:(g:string,r:string)=>Promise<void>;sendMessage:(t:string)=>Promise<void>;addMemory:(l:string,v:string,c:'context'|'preferences')=>Promise<void>};const C=createContext<Ctx|null>(null)
export function goalProgress(g:Goal){return g.tasks.length?Math.round(g.tasks.filter(t=>t.done).length/g.tasks.length*100):0}
function mapGoal(g:any,tasks:any[]):Goal{return{id:g.id,title:g.title,description:g.description||'',deadline:g.deadline||'',category:g.category||'Personal',outcomes:g.outcomes||[],milestones:g.milestones||[],tasks:tasks.filter(t=>t.goal_id===g.id).map(t=>({id:t.id,title:t.title,due:t.due_date||'',duration:t.duration||'30 min',done:!!t.done,adjusted:!!t.adjusted,purpose:t.purpose||'',steps:t.steps||[],result:t.result||''}))}}
export function LifePilotProvider({children}:{children:React.ReactNode}){const[goals,setGoals]=useState<Goal[]>([]),[memories,setMemories]=useState<MemoryItem[]>([]),[messages,setMessages]=useState<ChatMessage[]>([]),[activity,setActivity]=useState<Activity[]>([]),[isThinking,setThinking]=useState(false);const sb=createClient();const refresh=useCallback(async()=>{const{data:{user}}=await sb.auth.getUser();if(!user)return;const [gs,ts,ms,cs,as]=await Promise.all([sb.from('goals').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),sb.from('tasks').select('*').eq('user_id',user.id).order('due_date'),sb.from('memories').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),sb.from('agent_messages').select('*').eq('user_id',user.id).order('created_at'),sb.from('activity').select('*').eq('user_id',user.id).order('created_at',{ascending:false})]);setGoals((gs.data||[]).map(g=>mapGoal(g,ts.data||[])));setMemories((ms.data||[]).map(m=>({id:m.id,category:m.category,label:m.label,value:m.value,source:m.source||'LifePilot'})));setMessages((cs.data||[]).map(m=>({id:m.id,role:m.role,content:m.content,time:m.created_at})));setActivity((as.data||[]).map(a=>({id:a.id,kind:a.kind,title:a.title,detail:a.detail||'',time:a.created_at})))},[]);useEffect(()=>{void refresh()},[refresh]);
const createGoal=useCallback(async(title:string,details:string)=>{setThinking(true);try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,details})});const plan=await r.json();if(!r.ok)throw new Error(plan.error||'Could not create plan.');const{data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Please sign in again.');const{data:g,error}=await sb.from('goals').insert({user_id:user.id,title,description:details,category:plan.category||'Personal',deadline:addDays(TODAY,30),outcomes:plan.outcomes||[],milestones:plan.milestones||[]}).select().single();if(error)throw error;const rows=(plan.tasks||[]).map((t:any)=>({user_id:user.id,goal_id:g.id,title:t.title,due_date:addDays(TODAY,Math.max(0,Number(t.day)-1)),duration:t.duration||'30 min',done:false,adjusted:false,purpose:t.purpose||'',steps:Array.isArray(t.steps)?t.steps:[],result:t.result||''}));const{error:te}=await sb.from('tasks').insert(rows);if(te)throw te;await sb.from('activity').insert({user_id:user.id,kind:'created',title:`Created goal: ${title}`,detail:`${rows.length} tasks generated.`});await refresh();return g.id}finally{setThinking(false)}},[refresh]);
const toggleTask=useCallback(async(goalId:string,taskId:string)=>{const g=goals.find(x=>x.id===goalId),t=g?.tasks.find(x=>x.id===taskId);if(!t)return;const{data:{user}}=await sb.auth.getUser();if(!user)return;const done=!t.done;const{error}=await sb.from('tasks').update({done}).eq('id',taskId).eq('user_id',user.id);if(error)throw error;await sb.from('activity').insert({user_id:user.id,kind:'completed',title:done?`Completed: ${t.title}`:`Reopened: ${t.title}`,detail:g?.title||''});await refresh()},[goals,refresh]);
const replanGoal=useCallback(async(goalId:string,reason:string)=>{const g=goals.find(x=>x.id===goalId);if(!g)throw new Error('Goal not found.');setThinking(true);try{const r=await fetch('/api/replan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:g,tasks:g.tasks,reason})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Could not replan.');const{data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Please sign in again.');const completed=new Set(g.tasks.filter(t=>t.done).map(t=>t.title.toLowerCase()));await sb.from('tasks').delete().eq('goal_id',goalId).eq('user_id',user.id);const rows=(result.tasks||[]).map((t:any)=>({user_id:user.id,goal_id:goalId,title:t.title,due_date:addDays(TODAY,Math.max(0,Number(t.day)-1)),duration:t.duration||'30 min',done:completed.has(String(t.title).toLowerCase()),adjusted:true,purpose:t.purpose||'',steps:Array.isArray(t.steps)?t.steps:[],result:t.result||''}));await sb.from('tasks').insert(rows);await sb.from('activity').insert({user_id:user.id,kind:'replanned',title:`Replanned: ${g.title}`,detail:result.summary});await refresh()}finally{setThinking(false)}},[goals,refresh]);
const addMemory=useCallback(async(label:string,value:string,category:'context'|'preferences')=>{const{data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from('memories').insert({user_id:user.id,category,label,value,source:'LifePilot'});await refresh()},[refresh]);
const sendMessage=useCallback(async(text:string)=>{const clean=text.trim();if(!clean)return;setThinking(true);try{const{data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Please sign in again.');await sb.from('agent_messages').insert({user_id:user.id,role:'user',content:clean});const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:clean,goals,memory:memories,history:messages.slice(-10)})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Agent unavailable.');await sb.from('agent_messages').insert({user_id:user.id,role:'assistant',content:body.response});await refresh()}finally{setThinking(false)}},[goals,memories,messages,refresh]);const value=useMemo(()=>({goals,memories,messages,activity,isThinking,createGoal,toggleTask,replanGoal,sendMessage,addMemory}),[goals,memories,messages,activity,isThinking,createGoal,toggleTask,replanGoal,sendMessage,addMemory]);return <C.Provider value={value}>{children}</C.Provider>}
export function useLifePilot(){const v=useContext(C);if(!v)throw new Error('LifePilotProvider missing');return v}
